package ca.ubc.partyallthetime.bcmixr.shared;

import java.io.Serializable;
import java.util.ArrayList;

import javax.persistence.Id;

import ca.ubc.partyallthetime.bcmixr.client.AlcoholIngredient;

public class Recipe implements Serializable {

	// generated by eclipse. apparently, specifying a serialVersionUID just prevents certain bugs later. 
	private static final long serialVersionUID = 1938118796268143312L;
	
	@Id
	Long id;
	
	private String title;
	private ArrayList<Ingredient> ingredients = new ArrayList<Ingredient>();
	private ArrayList<AlcoholIngredient> alcohol = new ArrayList<AlcoholIngredient>();
	private String directions;
	
	public Recipe() {
		this.title = "Enter a Recipe Name";
		this.directions = "";
	}
	
	public void addAlcohol(AlcoholIngredient alc) {
		alcohol.add(alc);
	}
	
	public void addIngredient(Ingredient in) {
		ingredients.add(in);
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public ArrayList<Ingredient> getIngredients() {
		return ingredients;
	}

	public void setIngredients(ArrayList<Ingredient> ingredients) {
		this.ingredients = ingredients;
	}

	public String getDirections() {
		return directions;
	}

	public void setDirections(String directions) {
		this.directions = directions;
	}
	
	public ArrayList<AlcoholIngredient> getAlcohol() {
		return alcohol;
	}

	public void setAlcohol(ArrayList<AlcoholIngredient> alcohol) {
		this.alcohol = alcohol;
	}
}
