package ca.ubc.partyallthetime.bcmixr.server;

import java.io.Serializable;

import javax.persistence.Id;

public class RecipeRating implements Serializable {

	private static final long serialVersionUID = 6141774518291976833L; // generated by eclipse. 
	
	@Id 
    String recipeTitle; // Can be Long, long, or String
	private int upVotes;
	private int downVotes;
	public String getRecipeTitle() {
		return recipeTitle;
	}
	public void setRecipeTitle(String recipeTitle) {
		this.recipeTitle = recipeTitle;
	}
	public int getUpVotes() {
		return upVotes;
	}
	public void setUpVotes(int upVotes) {
		this.upVotes = upVotes;
	}
	public int getDownVotes() {
		return downVotes;
	}
	public void setDownVotes(int downVotes) {
		this.downVotes = downVotes;
	}
	
	
	
	
	
}
